blank_issues_enabled: false
contact_links:
  - name: GameMaker Account Support
    url: https://contact.gamemaker.io/contact-us
    about: Contact the Helpdesk if you're having trouble with your GameMaker account.
