blank_issues_enabled: false
contact_links:
  - name: GameMaker Bugs
    url: https://github.com/YoYoGames/GameMaker-Bugs/issues
    about: Do not report general GameMaker issues in this extension's space - instead, follow the link here to report them properly.
  - name: GameMaker Account Support
    url: https://contact.gamemaker.io/contact-us
    about: Contact the Helpdesk if you're having trouble with your GameMaker account.
