name: Extension Bug
description: Report a bug that only happens when the latest version of this extension is in your project
labels: ["Steamworks","extension"]
type: "Extension Bug"
body:
  - type: markdown
    attributes:
      value: |
        Search for any existing reports of this bug first! (If one exists, DO NOT file yours now - add a thumbs-up/comment on the existing report.)
       
        Most fields need to be filled-in before you can submit, as it's all required information to us confirm and fix this bug.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a thorough description of the bug. You may paste any relevant screenshots in. DO NOT paste more than a couple of lines of code (send a sample project instead!). DO NOT add a web URL and assume we will read any external discussion to work the bug ourselves, as we will almost certainly just close the report.
    validations:
      required: true
      
  - type: input
    id: expected
    attributes:
      label: Expected Change
      description: If it is not obvious from your Description text, what difference would you expect to see once this is fixed?
    validations:
      required: false
      
  - type: input
    id: sample
    attributes:
      label: Sample Package
      description: Recreate the problem and then use the Help > Upload a Bug Sample tool inside GameMaker. Ideally, say yes to including your project which shows the issue! Then paste the download URL into the box below.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Add detailed, ordered steps saying how someone else can recreate this bug (add as many steps into the middle as you require)
      value: |
        1. Start GameMaker
        2. 
        3. 
        4. See the issue
    validations:
      required: true
      
  - type: dropdown
    id: repro-rate
    attributes:
      label: How reliably can you recreate this issue using your steps above?
      options:
        - Always
        - Most Times
        - Only Sometimes
        - Rarely
        - Only Ever Happened Once 
    validations:
      required: true
      
  - type: input
    id: gm-version
    attributes:
      label: Which version of GameMaker are you reporting this issue for?
      description: Double-click or right-click the version number in the top-right corner of GameMaker and then paste the version number here. 
    validations:
      required: true
    
  - type: dropdown
    id: platforms
    attributes:
      label: Which platform(s) are you seeing the problem on?
      multiple: true
      options: 
        - Windows
        - macOS
        - Ubuntu
        - Android
        - iOS
        - tvOS
        - HTML5
        - GX.games
        - PlayStation 4
        - PlayStation 5
        - Switch
        - Xbox (GDK)
    validations:
      required: true
          
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
