name: Documentation Bug
description: Report a typo, incorrect information, or an addition that you require to be made to this extension's documentation
labels: ["Steamworks","extension","documentation"]
type: "Docs Bug"
body:
  - type: markdown
    attributes:
      value: |
        Search for any existing reports of this bug first! (If one exists, DO NOT file yours now - add a thumbs-up/comment on the existing report.)
       
        Most fields need to be filled-in before you can submit, as it's all required information to us confirm and fix this bug.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a thorough description of the problem/what you want added to the docs. You may paste any relevant screenshots and links in; however, DO NOT simply add a web URL and assume we will read any external discussion, as we will almost certainly just close the report.
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location Of The Problem
      description: Paste in the website URL for the page where you want the change to be made
    validations:
      required: false

  - type: input
    id: expected
    attributes:
      label: Expected Change
      description: If it is not obvious from your Description text, what difference would you expect to see once this is fixed?
    validations:
      required: false
          
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
