
enum STEAMWORKS_FRIENDS_FLAGS
{
	NONE = 0x00,
	BLOCKED = 0x01,
	FRIENDSHIP_REQUESTED	= 0x02,
	IMMEDIATE = 0x04,			// "REGULAR" FRIEND
	CLAN_MEMBER = 0x08,
	ON_GAME_SERVER = 0x10,	
	// HAS_PLAYED_WITH = 0x20,	// NOT CURRENTLY USED
	// FRIEND_OF_FRIEND = 0x40, // NOT CURRENTLY USED
	REQUESTING_FRIENDSHIP = 0x80,
	REQUESTING_INFO = 0x100,
	IGNORED	= 0x200,
	IGNORED_FRIEND = 0x400,
	// SUGGESTED = 0x800,	// NOT USED
	CHAT_MEMBER = 0x1000,
	ALL = 0xFFFF,
};


enum STEAMWORKS_PERSONA_STATE
{
	OFFLINE = 0,			// FRIEND IS NOT CURRENTLY LOGGED ON
	ONLINE = 1,			// FRIEND IS LOGGED ON
	BUSY = 2,			// USER IS ON, BUT BUSY
	AWAY = 3,			// AUTO-AWAY FEATURE
	SNOOZE = 4,			// AUTO-AWAY FOR A LONG TIME
	LOOKING_TO_TRADE = 5,	// ONLINE, TRADING
	LOOKING_TO_PLAY = 6,	// ONLINE, WANTING TO PLAY
	INVISIBLE = 7,		// ONLINE, BUT APPEARS OFFLINE TO FRIENDS.  THIS STATUS IS NEVER PUBLISHED TO CLIENTS.
	MAX,
};
